# Generated by Django 2.2 on 2021-07-11 16:32

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='NA', max_length=50)),
                ('experience', models.CharField(default='NA', max_length=50)),
                ('city', models.CharField(default='NA', max_length=50)),
                ('state', models.CharField(default='NA', max_length=50)),
                ('country', models.CharField(default='NA', max_length=50)),
                ('phone', models.CharField(default='NA', max_length=20)),
                ('bio', models.TextField(default='NA')),
                ('image', models.ImageField(default='profile_pics/default.png', upload_to=accounts.models.profile_pic_path)),
                ('followers', models.ManyToManyField(blank=True, null=True, related_name='followers', to='accounts.Users')),
                ('following', models.ManyToManyField(blank=True, null=True, related_name='following', to='accounts.Users')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Users')),
            ],
        ),
    ]
