# Generated by Django 2.2 on 2021-07-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210713_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='author',
            new_name='photographer',
        ),
        migrations.RenameField(
            model_name='textpost',
            old_name='author',
            new_name='photographer',
        ),
    ]
